---
- name: Backup the network interface configuration
  copy:
    src: /etc/sysconfig/network-scripts/ifcfg-enp0s3  # Cambia esto por el nombre de tu interfaz
    dest: /etc/sysconfig/network-scripts/backup_ifcfg-enp0s3_{{ ansible_date_time.iso8601 }}
    remote_src: true

- name: Configure network interface
  template:
    src: templates/ifcfg-enp0s3.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3